inherit_from: "configs/paper/tum/base_config.yaml"

Dataset:
  dataset_path: "/home/jizong/Workspace/dConstruct/data/example_data/subregion"
  Calibration:
    fx: 560.1595530518094
    fy: 559.8752636760909
    cx: 659.5430672762923
    cy: 354.5327242397341
    k1: 0
    k2: 0
    p1: 0
    p2: 0
    k3: 0
    width: 1280
    height: 720
    depth_scale: 1
    distorted: False



